apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-fine-tuning-
spec:
  entrypoint: DAG-t5-fine-tuning
  templates:
  - name: data-preprocessing-template
    container:
      image: maaz112233/pirlib
      command:
      - python
      - -m
      - pirlib.backends.argo_batch
      - node
      - gASVdQIAAAAAAACMCnBpcmxpYi5waXKUjAROb2RllJOUKYGUfZQojAJpZJSMEmRhdGFfcHJlcHJvY2Vzc2luZ5SMC2VudHJ5cG9pbnRzlH2UjARtYWlulGgAjApFbnRyeXBvaW50lJOUKYGUfZQojAd2ZXJzaW9ulIwCdjGUjAdoYW5kbGVylIwxZXhhbXBsZXMudDVfZmluZV90dW5pbmcudHVuaW5nOmRhdGFfcHJlcHJvY2Vzc2luZ5SMB3J1bnRpbWWUjApweXRob246My44lIwHY29kZXVybJROjAVpbWFnZZSMEW1hYXoxMTIyMzMvcGlybGlilHVic4wJZnJhbWV3b3JrlE6MBmNvbmZpZ5R9lIwFdGltZXKUiXOMBmlucHV0c5RdlGgAjAVJbnB1dJSTlCmBlH2UKGgFjAdkYXRhc2V0lIwGaW90eXBllIwJRElSRUNUT1JZlIwGc291cmNllGgAjApEYXRhU291cmNllJOUKYGUfZQojAdub2RlX2lklE6MC3N1YmdyYXBoX2lklE6MCW91dHB1dF9pZJROjA5ncmFwaF9pbnB1dF9pZJSMB2RhdGFzZXSUdWKMBG1ldGGUaACMCE1ldGFkYXRhlJOUKYGUfZQojARuYW1llIwHZGF0YXNldJSMC2Fubm90YXRpb25zlE51YnViYYwHb3V0cHV0c5RdlGgAjAZPdXRwdXSUk5QpgZR9lChoBYwGcmV0dXJulGgijAlESVJFQ1RPUlmUaC5oMCmBlH2UKGgzjAZyZXR1cm6UaDVOdWJ1YmFoLmgwKYGUfZQoaDOMEmRhdGFfcHJlcHJvY2Vzc2luZ5RoNU51YnViLg==
      - gASVigAAAAAAAABdlIwKcGlybGliLnBpcpSMCkdyYXBoSW5wdXSUk5QpgZR9lCiMAmlklIwHZGF0YXNldJSMBmlvdHlwZZSMCURJUkVDVE9SWZSMBG1ldGGUaAGMCE1ldGFkYXRhlJOUKYGUfZQojARuYW1llIwHZGF0YXNldJSMC2Fubm90YXRpb25zlE51YnViYS4=
      volumeMounts:
      - name: node-outputs
        mountPath: /mnt/node_outputs
      - name: dataset
        mountPath: /mnt/graph_inputs/dataset
    volumes:
    - name: node-outputs
      nfs:
        server: k8s-master.cm.cluster
        path: /home/maaz/pirlib/examples/t5_fine_tuning/outputs
        readOnly: no
    - name: dataset
      nfs:
        server: k8s-master.cm.cluster
        path: /home/maaz/pirlib/examples/t5_fine_tuning/inputs
        readOnly: yes
  - name: fine-tuning-template
    container:
      image: maaz112233/pirlib
      command:
      - python
      - -m
      - pirlib.backends.argo_batch
      - node
      - gASV2AIAAAAAAACMCnBpcmxpYi5waXKUjAROb2RllJOUKYGUfZQojAJpZJSMC2ZpbmVfdHVuaW5nlIwLZW50cnlwb2ludHOUfZSMBG1haW6UaACMCkVudHJ5cG9pbnSUk5QpgZR9lCiMB3ZlcnNpb26UjAJ2MZSMB2hhbmRsZXKUjCpleGFtcGxlcy50NV9maW5lX3R1bmluZy50dW5pbmc6ZmluZV90dW5pbmeUjAdydW50aW1llIwKcHl0aG9uOjMuOJSMB2NvZGV1cmyUTowFaW1hZ2WUjBFtYWF6MTEyMjMzL3BpcmxpYpR1YnOMCWZyYW1ld29ya5ROjAZjb25maWeUfZSMBXRpbWVylIlzjAZpbnB1dHOUXZQoaACMBUlucHV0lJOUKYGUfZQoaAWMCWRhdGFfcGF0aJSMBmlvdHlwZZSMCURJUkVDVE9SWZSMBnNvdXJjZZRoAIwKRGF0YVNvdXJjZZSTlCmBlH2UKIwHbm9kZV9pZJSMEmRhdGFfcHJlcHJvY2Vzc2luZ5SMC3N1YmdyYXBoX2lklE6MCW91dHB1dF9pZJSMBnJldHVybpSMDmdyYXBoX2lucHV0X2lklE51YowEbWV0YZRoAIwITWV0YWRhdGGUk5QpgZR9lCiMBG5hbWWUjAlkYXRhX3BhdGiUjAthbm5vdGF0aW9uc5ROdWJ1YmgeKYGUfZQoaAWMB2RhdGFzZXSUaCKMCURJUkVDVE9SWZRoJGgmKYGUfZQoaClOaCtOaCxOaC6MB2RhdGFzZXSUdWJoL2gxKYGUfZQoaDSMB2RhdGFzZXSUaDZOdWJ1YmWMB291dHB1dHOUXZRoAIwGT3V0cHV0lJOUKYGUfZQoaAWMBnJldHVybpRoIowJRElSRUNUT1JZlGgvaDEpgZR9lChoNIwGcmV0dXJulGg2TnVidWJhaC9oMSmBlH2UKGg0jAtmaW5lX3R1bmluZ5RoNk51YnViLg==
      - gASVigAAAAAAAABdlIwKcGlybGliLnBpcpSMCkdyYXBoSW5wdXSUk5QpgZR9lCiMAmlklIwHZGF0YXNldJSMBmlvdHlwZZSMCURJUkVDVE9SWZSMBG1ldGGUaAGMCE1ldGFkYXRhlJOUKYGUfZQojARuYW1llIwHZGF0YXNldJSMC2Fubm90YXRpb25zlE51YnViYS4=
      volumeMounts:
      - name: node-outputs
        mountPath: /mnt/node_outputs
      - name: dataset
        mountPath: /mnt/graph_inputs/dataset
    volumes:
    - name: node-outputs
      nfs:
        server: k8s-master.cm.cluster
        path: /home/maaz/pirlib/examples/t5_fine_tuning/outputs
        readOnly: no
    - name: dataset
      nfs:
        server: k8s-master.cm.cluster
        path: /home/maaz/pirlib/examples/t5_fine_tuning/inputs
        readOnly: yes
  - name: model-distillation-template
    container:
      image: maaz112233/pirlib
      command:
      - python
      - -m
      - pirlib.backends.argo_batch
      - node
      - gASVdQMAAAAAAACMCnBpcmxpYi5waXKUjAROb2RllJOUKYGUfZQojAJpZJSMEm1vZGVsX2Rpc3RpbGxhdGlvbpSMC2VudHJ5cG9pbnRzlH2UjARtYWlulGgAjApFbnRyeXBvaW50lJOUKYGUfZQojAd2ZXJzaW9ulIwCdjGUjAdoYW5kbGVylIwxZXhhbXBsZXMudDVfZmluZV90dW5pbmcudHVuaW5nOm1vZGVsX2Rpc3RpbGxhdGlvbpSMB3J1bnRpbWWUjApweXRob246My44lIwHY29kZXVybJROjAVpbWFnZZSMEW1hYXoxMTIyMzMvcGlybGlilHVic4wJZnJhbWV3b3JrlE6MBmNvbmZpZ5R9lIwFdGltZXKUiXOMBmlucHV0c5RdlChoAIwFSW5wdXSUk5QpgZR9lChoBYwVZmluZV90dW5lZF9tb2RlbF9wYXRolIwGaW90eXBllIwJRElSRUNUT1JZlIwGc291cmNllGgAjApEYXRhU291cmNllJOUKYGUfZQojAdub2RlX2lklIwLZmluZV90dW5pbmeUjAtzdWJncmFwaF9pZJROjAlvdXRwdXRfaWSUjAZyZXR1cm6UjA5ncmFwaF9pbnB1dF9pZJROdWKMBG1ldGGUaACMCE1ldGFkYXRhlJOUKYGUfZQojARuYW1llIwVZmluZV90dW5lZF9tb2RlbF9wYXRolIwLYW5ub3RhdGlvbnOUTnVidWJoHimBlH2UKGgFjAlkYXRhX3BhdGiUaCKMCURJUkVDVE9SWZRoJGgmKYGUfZQoaCmMEmRhdGFfcHJlcHJvY2Vzc2luZ5RoK05oLIwGcmV0dXJulGguTnViaC9oMSmBlH2UKGg0jAlkYXRhX3BhdGiUaDZOdWJ1YmgeKYGUfZQoaAWMB2RhdGFzZXSUaCKMCURJUkVDVE9SWZRoJGgmKYGUfZQoaClOaCtOaCxOaC6MB2RhdGFzZXSUdWJoL2gxKYGUfZQoaDSMB2RhdGFzZXSUaDZOdWJ1YmWMB291dHB1dHOUXZRoAIwGT3V0cHV0lJOUKYGUfZQoaAWMBnJldHVybpRoIowJRElSRUNUT1JZlGgvaDEpgZR9lChoNIwGcmV0dXJulGg2TnVidWJhaC9oMSmBlH2UKGg0jBJtb2RlbF9kaXN0aWxsYXRpb26UaDZOdWJ1Yi4=
      - gASVigAAAAAAAABdlIwKcGlybGliLnBpcpSMCkdyYXBoSW5wdXSUk5QpgZR9lCiMAmlklIwHZGF0YXNldJSMBmlvdHlwZZSMCURJUkVDVE9SWZSMBG1ldGGUaAGMCE1ldGFkYXRhlJOUKYGUfZQojARuYW1llIwHZGF0YXNldJSMC2Fubm90YXRpb25zlE51YnViYS4=
      volumeMounts:
      - name: node-outputs
        mountPath: /mnt/node_outputs
      - name: dataset
        mountPath: /mnt/graph_inputs/dataset
    volumes:
    - name: node-outputs
      nfs:
        server: k8s-master.cm.cluster
        path: /home/maaz/pirlib/examples/t5_fine_tuning/outputs
        readOnly: no
    - name: dataset
      nfs:
        server: k8s-master.cm.cluster
        path: /home/maaz/pirlib/examples/t5_fine_tuning/inputs
        readOnly: yes
  - name: generate-output-template
    container:
      image: maaz112233/pirlib
      command:
      - python
      - -m
      - pirlib.backends.argo_batch
      - node
      - gASV9gIAAAAAAACMCnBpcmxpYi5waXKUjAROb2RllJOUKYGUfZQojAJpZJSMD2dlbmVyYXRlX291dHB1dJSMC2VudHJ5cG9pbnRzlH2UjARtYWlulGgAjApFbnRyeXBvaW50lJOUKYGUfZQojAd2ZXJzaW9ulIwCdjGUjAdoYW5kbGVylIwuZXhhbXBsZXMudDVfZmluZV90dW5pbmcudHVuaW5nOmdlbmVyYXRlX291dHB1dJSMB3J1bnRpbWWUjApweXRob246My44lIwHY29kZXVybJROjAVpbWFnZZSMEW1hYXoxMTIyMzMvcGlybGlilHVic4wJZnJhbWV3b3JrlE6MBmNvbmZpZ5R9lIwFdGltZXKUiXOMBmlucHV0c5RdlChoAIwFSW5wdXSUk5QpgZR9lChoBYwHZGF0YXNldJSMBmlvdHlwZZSMCURJUkVDVE9SWZSMBnNvdXJjZZRoAIwKRGF0YVNvdXJjZZSTlCmBlH2UKIwHbm9kZV9pZJROjAtzdWJncmFwaF9pZJROjAlvdXRwdXRfaWSUTowOZ3JhcGhfaW5wdXRfaWSUjAdkYXRhc2V0lHVijARtZXRhlGgAjAhNZXRhZGF0YZSTlCmBlH2UKIwEbmFtZZSMB2RhdGFzZXSUjAthbm5vdGF0aW9uc5ROdWJ1YmgeKYGUfZQoaAWMEmZpbmVfdHVuaW5nX291dHB1dJRoIowJRElSRUNUT1JZlGgkaCYpgZR9lChoKYwSbW9kZWxfZGlzdGlsbGF0aW9ulGgqTmgrjAZyZXR1cm6UaCxOdWJoLmgwKYGUfZQoaDOMEmZpbmVfdHVuaW5nX291dHB1dJRoNU51YnViZYwHb3V0cHV0c5RdlGgAjAZPdXRwdXSUk5QpgZR9lChoBYwGcmV0dXJulGgijAlESVJFQ1RPUlmUaC5oMCmBlH2UKGgzjAZyZXR1cm6UaDVOdWJ1YmFoLmgwKYGUfZQoaDOMD2dlbmVyYXRlX291dHB1dJRoNU51YnViLg==
      - gASVigAAAAAAAABdlIwKcGlybGliLnBpcpSMCkdyYXBoSW5wdXSUk5QpgZR9lCiMAmlklIwHZGF0YXNldJSMBmlvdHlwZZSMCURJUkVDVE9SWZSMBG1ldGGUaAGMCE1ldGFkYXRhlJOUKYGUfZQojARuYW1llIwHZGF0YXNldJSMC2Fubm90YXRpb25zlE51YnViYS4=
      volumeMounts:
      - name: node-outputs
        mountPath: /mnt/node_outputs
      - name: dataset
        mountPath: /mnt/graph_inputs/dataset
    volumes:
    - name: node-outputs
      nfs:
        server: k8s-master.cm.cluster
        path: /home/maaz/pirlib/examples/t5_fine_tuning/outputs
        readOnly: no
    - name: dataset
      nfs:
        server: k8s-master.cm.cluster
        path: /home/maaz/pirlib/examples/t5_fine_tuning/inputs
        readOnly: yes
  - name: t5-fine-tuning-template
    container:
      image: maaz112233/pirlib
      command:
      - python
      - -m
      - pirlib.backends.argo_batch
      - graph
      - gASV/QAAAAAAAABdlIwKcGlybGliLnBpcpSMC0dyYXBoT3V0cHV0lJOUKYGUfZQojAJpZJSMBnJldHVybpSMBmlvdHlwZZSMCURJUkVDVE9SWZSMBnNvdXJjZZRoAYwKRGF0YVNvdXJjZZSTlCmBlH2UKIwHbm9kZV9pZJSMD2dlbmVyYXRlX291dHB1dJSMC3N1YmdyYXBoX2lklE6MCW91dHB1dF9pZJSMBnJldHVybpSMDmdyYXBoX2lucHV0X2lklE51YowEbWV0YZRoAYwITWV0YWRhdGGUk5QpgZR9lCiMBG5hbWWUjAZyZXR1cm6UjAthbm5vdGF0aW9uc5ROdWJ1YmEu
      volumeMounts:
      - name: node-outputs
        mountPath: /mnt/node_outputs
      - name: dataset
        mountPath: /mnt/graph_inputs/dataset
      - name: graph-outputs
        mountPath: /mnt/graph_outputs
    volumes:
    - name: node-outputs
      nfs:
        server: k8s-master.cm.cluster
        path: /home/maaz/pirlib/examples/t5_fine_tuning/outputs
        readOnly: no
    - name: dataset
      nfs:
        server: k8s-master.cm.cluster
        path: /home/maaz/pirlib/examples/t5_fine_tuning/inputs
        readOnly: yes
    - name: graph-outputs
      nfs:
        server: k8s-master.cm.cluster
        path: /home/maaz/pirlib/examples/t5_fine_tuning/outputs
        readOnly: no
  - name: DAG-t5-fine-tuning
    dag:
      tasks:
      - name: data-preprocessing
        template: data-preprocessing-template
        dependencies: []
      - name: fine-tuning
        template: fine-tuning-template
        dependencies:
        - data-preprocessing
      - name: model-distillation
        template: model-distillation-template
        dependencies:
        - fine-tuning
        - data-preprocessing
      - name: generate-output
        template: generate-output-template
        dependencies:
        - model-distillation
      - name: t5-fine-tuning
        template: t5-fine-tuning-template
        dependencies:
        - data-preprocessing
        - fine-tuning
        - model-distillation
        - generate-output
